### PR TITLE
Add several devtools and also apply role to c-nodes

### PR DESCRIPTION
**Pull request by jantrienes**
This PR installs several trivial devools. After discussion with @enasca, we think that this role may also be suitable for the c-nodes. So this PR also renames the role to reflect it in the naming.

I do not know how to test this PR. Is that something you could assist with @hfrSchmidt?

### CODE REVIEW

**Review by enasca — APPROVED** [review]
I've applied it to the `managed_cluster_gpu` nodes. Hendrik should be able to do the same for the `managed_cluster_compute` group.

**Review by hfrSchmidt — APPROVED** [review]
Alright. Looks harmless.

**Comment by hfrSchmidt** [comment]
I'll check out the branch and test this with one of the c-nodes

**Comment by hfrSchmidt** [comment]
The changes are applied to the managed_cluster_compute group as well. I'm merging the PR.

**Pull request merged**
