### PR TITLE
feat: added snakemake configuration profiles

### PR DESCRIPTION
**Pull request by johanneskoester**

### CODE REVIEW

**Comment by enasca** [comment]
I reworked the commit to fix a couple of things and make it similar to existing ones.

- Directories are created before attempting to create files in them.
- File contents are in files instead of inline.
- Added a separation between a main task files and the actual tasks (to make it easier to add things in the future)
- Added tags to enable targeting this role.

**Comment by enasca** [comment]
@johanneskoester Do you plan to add tasks to install snakemake? Also note that the role won't be functional until it's referenced by `site.yml`. You can choose whether to target all nodes or a specific category such as slurm nodes.

**Comment by johanneskoester** [comment]
Thanks @enasca. No plans to install Snakemake. That has to happen via mamba, and the global mamba is not reliable due to locking issues on NFS. Every user has to install their own mamba and from there install Snakemake.

**Comment by enasca** [comment]
I think it's easier to make the profile file into a template which adds the `slurm: true` line only on slurm nodes.

**Comment by enasca** [comment]
Should be ready now. After Hendrik's approval, we can apply the role cluster-wide.

**Review by hfrSchmidt — APPROVED** [review]

**Comment by enasca** [comment]
I'm applying this to slurm nodes and gpu nodes.

**Pull request merged**
