### PR TITLE
Slurm compute nodes

### PR DESCRIPTION
**Pull request by enasca**
This allows us to install slurm 19 on Ubuntu 20.04 and 22.04 hosts. As explained in the first commit message, this is just an initial implementation. I'll work on polishing this node and adding something for the controller node, particularly regarding how to distribute the `munge.key`, `slurm.conf` and the custom deb packages across the cluster.

### CODE REVIEW

**Comment by enasca** [comment]
The role is now able to generate and distribute `munge.key` and `slurm.conf` to the slurm nodes.

**Comment by enasca** [comment]
The next item on my list is preparing a small apt repository to distribute the custom-built slurmd package.

**Comment by enasca** [comment]
The role can now create repository metadata for distributing the deb packages. Now that there's basic functionality, we should be ready to merge.

**Comment by enasca** [comment]
The role can now count GPUs on each node and generate the slurm configuration files accordingly.

**Review by hfrSchmidt — APPROVED** [review]
Awesome! Thanks!
What's with this module problem with community.general.timezone?
It would probably be a good idea to talk this through together.

**Comment by enasca** [comment]
Nothing to do with timezone. The linter error is being fixed with #56. Aside from that, of course we should meet and go through the role together.

**Pull request merged**
