### PR TITLE
Fix the miniconda shell profile

### PR DESCRIPTION
**Pull request by enasca**
The way miniconda was added to `PATH` was wrong. It masked the system python installation and wasn't sufficient to make `conda activate` work. The ready-made shell profile script from the installation directory is now used instead. The actual change is in 444db9b, while the other commits are a refactor.

Since the role now creates `/etc/profile.d/miniconda.sh` as a symlink, it will fail on existing deployments where the path exists as a regular file. Here's a tiny playbook which fixes existing installations:

```
  tasks:
    - name: Remove the existing file
      ansible.builtin.file:
        path: /etc/profile.d/miniconda.sh
        state: absent
    - name: Create the symlink
      ansible.builtin.file:
        src: /opt/miniconda/etc/profile.d/conda.sh
        dest: /etc/profile.d/miniconda.sh
        state: link
        owner: root
        group: root
```

I'll apply the fix to the machines deployed by me.

### CODE REVIEW

**Comment by hfrSchmidt** [comment]
I'm not sure if we even want to continue to use miniconda. Is mambaforge not the preferred method in the meantime?
I guess the question behind this is: Is it really necessary to roll this out to all managed cluster machines?

**Comment by enasca** [comment]
Actually I don't know if we have a preferred method of deploying conda, but the `mambaforge` role isn't included in `site.yml`. The mml team currently uses miniconda. If you want to use mambaforge cluster-wide, I'm happy to switch. Let's have a chat.

**Comment by hfrSchmidt** [comment]
Hm. I'm currently trying to determine which solution has a good balance between future proof and amount of effort to put in. 
Let's discuss this in the next infrastructure meeting.

**Comment by enasca** [comment]
If I'm the only admin using miniconda, this should be safe to merge.

**Pull request merged**
